steps:
  - name: gcr.io/cloud-builders/docker
    args: ['build', '-t', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/favorita-api:$COMMIT_SHA', '.']
  - name: gcr.io/cloud-builders/docker
    args: ['push', '${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/favorita-api:$COMMIT_SHA']
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - favorita-forecast-api
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/favorita-api:$COMMIT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --no-allow-unauthenticated
substitutions:
  _REGION: europe-west1
  _REPOSITORY: ml-images
