apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: favorita-forecast-api
spec:
  template:
    spec:
      serviceAccountName: REPLACE_WITH_SERVICE_ACCOUNT
      containers:
        - image: REPLACE_WITH_ARTIFACT_REGISTRY_IMAGE
          ports:
            - containerPort: 8000
          resources:
            limits:
              cpu: "2"
              memory: 2Gi
